version: '3'
services:
  discord-bot:
    build:
      context: .
      dockerfile: dockerfile  
    environment:
      - BOT_TOKEN = ${BOT_TOKEN}
      - GUILD_ID = ${GUILD_ID}
      - CHANNEL_ID = ${CHANNEL_ID}
      - MC_IP = ${MC_IP}
      - OPENER_PORT = ${OPENER_PORT}
      - MC_PORT = ${MC_PORT}
    env_file:
      - .env.prod
    restart: always
    networks:
      - loa_network
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:16.2-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD = ${POSTGRES_PASSWORD}
      - POSTGRES_USER = ${POSTGRES_USER}
    ports:
    - '5432:5432'
    volumes:
    - postgres_db:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - loa_network
      
volumes:
  postgres_db:
    driver: local 

networks:
  loa_network:
    driver: bridge